### ISSUE TITLE
ERROR: No matching distribution found for pyenergyplus

### ISSUE THREAD

**Issue by bbartling** [Myoldmopar/EnergyPlusAPIHelper#5]
Hello,

Am trying to run the 08_server_advanced.py from the demos on Windows 10. I had this up and running a few months ago where it worked just fine I think using Python 3.10. Am trying it out again and run into the an issue below, the `pip install energyplus_api_helpers` went just fine but get this error when running the file:

```
> py  .\energyplus_api_helpers\demos\08_server_advanced.py        
Traceback (most recent call last):
  File "C:\Users\bbartling\OneDrive - Slipstream\Desktop\EnergyPlusAPIHelper\energyplus_api_helpers\demos\08_server_advanced.py", line 28, in <module>
    runner = RunConfig()
             ^^^^^^^^^^^
  File "C:\Users\bbartling\OneDrive - Slipstream\Desktop\EnergyPlusAPIHelper\energyplus_api_helpers\demos\08_server_advanced.py", line 12, in __init__
    self.api = self.e.get_api_instance()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bbartling\AppData\Local\Programs\Python\Python311\Lib\site-packages\energyplus_api_helpers\import_helper.py", line 45, in get_api_instance
    from pyenergyplus.api import EnergyPlusAPI
ModuleNotFoundError: No module named 'pyenergyplus'
PS C:\Users\bbartling\OneDrive - Slipstream\Desktop\EnergyPlusAPIHelper> py -m pip install pyenergyplus                                  
ERROR: Could not find a version that satisfies the requirement pyenergyplus (from versions: none)
ERROR: No matching distribution found for pyenergyplus

```

Thanks for any tips

**Comment by Myoldmopar** [comment]
`pyenergyplus` is not a distribution up on PyPi, that's the package that comes nested inside E+ when it is installed.  If you specified the path to the E+ install when you instantiated your API Helper class, it should have been able to find `pyenergyplus` inside that E+ installation.  Can you confirm the E+ install path is set properly there and reply back?  (FWIW I test this out on a weekly basis and it seems like it still works fine to me, no major changes on this demo or our API in a while...)

**Comment by bbartling** [comment]
Ah okay, sorry its been a while. My Eplus is installed here:

`C:\EnergyPlusV23-1-0`

Can you run that by me again how I reference this distribution when I run energyplus_api_helpers?

**Comment by Myoldmopar** [comment]
Sure, when you construct the class, just tell it where you installed E+:

For that demo specifically, just set your path around line 10 (as of today) [here](https://github.com/Myoldmopar/EnergyPlusAPIHelper/blob/main/energyplus_api_helpers/demos/08_server_advanced.py#L10):

```
class RunConfig:
    def __init__(self):
        self.e = EPlusAPIHelper(Path('C:/EnergyPlus-23-1-0'))
        self.idf_name = '5ZoneAirCooled.idf'
        self.api = self.e.get_api_instance()
```

**Comment by bbartling** [comment]
Sorry for the delay in the response, this is actually working for me and for noobs its nice to see the print out that script can reach the directory.

```
from flask import Flask
from pathlib import Path
from threading import Thread
from time import sleep
from energyplus_api_helpers.import_helper import EPlusAPIHelper
import os

directory_path = r"C:\EnergyPlusV23-1-0"

# List all contents of the directory
contents = os.listdir(directory_path)

for item in contents:
    print(item)


class RunConfig:
    def __init__(self):
        self.e = EPlusAPIHelper(Path(directory_path))
```
